name: Auto deploy
on:
  push:
    branches: [ main ]

jobs:
  # This workflow contains a single job called "rspec"
  auto_deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11.5
        ports: ["5432:5432"]
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    # install ruby(refer to .ruby-version)
    - uses: ruby/setup-ruby@v1
    # cache gems
    - uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: bundle-use-ruby-ubuntu-latest-2.7.0-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: bundle-use-ruby-ubuntu-latest-2.7.0-
    - name: bundle install
      run: |
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3
    - name: build app
      env:
        PGHOST: localhost
        PGUSER: postgres
        RAILS_ENV: test
        RAILS_MASTER_KEY: ${{  secrets.RAILS_MASTER_KEY  }}
      run: |
        bundle exec rails db:create
        bundle exec rails db:schema:load
    - name: run rspec
      env:
        PGHOST: localhost
        PGUSER: postgres
        RAILS_ENV: test
        RAILS_MASTER_KEY:  ${{  secrets.RAILS_MASTER_KEY  }}
      run: bundle exec rspec
    - name: Install SSH key
      uses: webfactory/ssh-agent@v0.4.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    - name: Deploy
      env:
        DEPLOY_PASSWORD:  ${{  secrets.DEPLOY_PASSWORD  }}
      run: bundle exec cap production deploy
