name: RSpec
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  rspec:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12-alpine
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
    - uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: bundle-use-ruby-ubuntu-latest-2.7.0-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: bundle-use-ruby-ubuntu-latest-2.7.0-
    - name: bundle install
      run: |
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3
    - name: build app
      env:
        PGHOST: localhost
        PGUSER: postgres
        PGPASSWORD: postgres
        RAILS_ENV: test
        RAILS_MASTER_KEY: ${{  secrets.RAILS_MASTER_KEY  }}
      run: |
        bundle exec rails db:create
        bundle exec rails db:schema:load
    - name: run rspec
      env:
        PGHOST: localhost
        PGUSER: postgres
        PGPASSWORD: postgres
        RAILS_ENV: test
        RAILS_MASTER_KEY:  ${{  secrets.RAILS_MASTER_KEY  }}
      run: bundle exec rspec
